### ISSUE TITLE
Cargo build fails

### ISSUE THREAD

**Issue by pistomat** [Will-Smith11/reconnaissance#1]
I wanted to try this project out, but couldn't build it due to what seems to be the update of revm v20.

Running `cargo build` produces total of 9 errors 

 ```
... 
Compiling reth-primitives v0.1.0 (https://github.com/paradigmxyz/reth.git#ff34c0ec)
error[E0432]: unresolved import revm_primitives::JumpMap
 --> /Users/.../.cargo/git/checkouts/reth-36d3ea1d1152b20c/ff34c0e/crates/primitives/src/account.rs:5:64
  |
5 | use revm_primitives::{Bytecode as RevmBytecode, BytecodeState, JumpMap};
  |                                                                ^^^^^^^ no JumpMap in the root
...
...
error: could not compile `reth-primitives` due to 9 previous errors
warning: build failed, waiting for other jobs to finish...
```

Reth commit ff34c0e builds just fine, the crate `primitives` includes `revm-primitives: v1.0.0`, but somehow if I try to build this repo, the error links to what seems to be the old v0.1.0 and fail to compile.

**Comment by pistomat** [comment]
Specifying the commit in `cargo.toml` should also help in the future

`reth-network = { git = "https://github.com/paradigmxyz/reth.git", rev = "bc0ce63" }`

**Comment by Will-Smith11** [comment]
Damn i didn't see this for the longest time. I locked the version to the old commit sry ab this
